// 工作树模块：action 声明是 CLI 命令、HTTP 路由、help 文案的唯一来源。
// 加一条操作 = 在 actions 里加一项，三端同时获得它。
//
// 本模块管理的工作树**真相在 git**（worktree list），不是本工具持有的集合，
// 因此不声明 resource、不硬套 CRUD——写操作是 rebase/fanout/remove 这些动词，
// 没有语义上的「update 一个工作树」。扩展文件（wt ext）则是完整的登记型集合。
// 人读渲染在 renders.js；业务在 service.js（barrel）与 svc/。
import * as service from './service.js';
import {
  renderWtList, renderWt, cdLine, renderRemove, renderConfig, renderInit,
  renderContext, renderExtList, renderDiscover, renderExtAdded, renderExtUpdated,
  renderExtRemoved, renderRebase, renderFanout,
} from './renders.js';
export default {
  id: 'worktrees',
  title: '工作树（= Web「工作树」页）',
  order: 15,
  view: () => import('./view.jsx'),

  actions: [
    {
      id: 'wt.init',
      cli: ['wt', 'init'],
      http: ['POST', '/api/wt/init'],
      summary: '初始化工作树机制：建根目录、按需登记 .gitignore',
      flags: {
        root: { type: 'string', hint: '工作树根目录' },
        'branch-prefix': { type: 'string' },
        'base-branch': { type: 'string' },
      },
      run: (ctx) =>
        service.initWorktree({
          worktreeRoot: ctx.root,
          branchPrefix: ctx['branch-prefix'],
          baseBranch: ctx['base-branch'],
        }),
      render: renderInit,
    },
    {
      id: 'wt.config.get',
      cli: ['wt', 'config'],
      http: ['GET', '/api/wt/config'],
      summary: '查看工作树模块配置',
      run: () => service.getConfig(),
      render: renderConfig,
    },
    {
      id: 'wt.config.set',
      cli: ['wt', 'config', 'set'],
      http: ['PATCH', '/api/wt/config'],
      summary: '修改分支前缀 / 基础分支 / 工作树根',
      flags: {
        root: { type: 'string', hint: '工作树根目录' },
        'branch-prefix': { type: 'string' },
        'base-branch': { type: 'string' },
      },
      run: (ctx) =>
        service.setConfig({
          worktreeRoot: ctx.root,
          branchPrefix: ctx['branch-prefix'],
          baseBranch: ctx['base-branch'],
        }),
      render: renderConfig,
    },
    {
      id: 'wt.list',
      cli: ['wt', 'list'],
      http: ['GET', '/api/wt/list'],
      summary: '工作树清单（含改动 / 领先落后 / 缺扩展）',
      flags: { base: { type: 'string', hint: '基础分支' } },
      run: (ctx) => service.listWorktrees({ base: ctx.base }),
      render: renderWtList,
    },
    {
      id: 'wt.get',
      cli: ['wt', 'get'],
      http: ['GET', '/api/wt/:ref'],
      summary: '查看单个工作树详情（提交记录 / 扩展文件）',
      args: ['ref'],
      run: (ctx) => service.getWorktree(ctx.ref),
      render: renderWt,
    },
    {
      id: 'wt.add',
      cli: ['wt', 'add'],
      http: ['POST', '/api/wt'],
      summary: '描述要做的事，创建分支与工作树',
      args: ['description'],
      flags: {
        name: { type: 'string', hint: '自定义会话名' },
        base: { type: 'string', hint: '起点分支' },
        root: { type: 'string', hint: '工作树根覆盖' },
        force: { type: 'boolean' },
      },
      run: (ctx) => service.addWorktree(ctx),
      render: cdLine,
    },
    {
      id: 'wt.checkout',
      cli: ['wt', 'checkout'],
      http: ['POST', '/api/wt/checkout'],
      summary: '把已存在的分支挂成新工作树',
      args: ['branch'],
      flags: {
        name: { type: 'string' },
        root: { type: 'string' },
        force: { type: 'boolean' },
      },
      run: (ctx) => service.checkoutWorktree(ctx),
      render: cdLine,
    },
    {
      id: 'wt.remove',
      cli: ['wt', 'remove'],
      http: ['DELETE', '/api/wt/:ref'],
      summary: '移除工作树；--branch 连分支一起删，脏树需 --force',
      args: ['ref'],
      flags: { branch: { type: 'boolean' }, force: { type: 'boolean' } },
      run: (ctx) => service.removeWorktree(ctx.ref, { branch: ctx.branch === true, force: ctx.force === true }),
      render: renderRemove,
    },
    {
      id: 'wt.switch',
      cli: ['wt', 'switch'],
      http: ['POST', '/api/wt/switch'],
      summary: '取得进入工作树的 cd 指令',
      args: ['ref'],
      run: (ctx) => service.switchWorktree(ctx.ref),
      render: (r) => `cd "${r.path}"`,
    },
    {
      id: 'wt.open',
      cli: ['wt', 'open'],
      http: ['POST', '/api/wt/open'],
      summary: '在系统文件管理器中打开工作树',
      args: ['ref'],
      run: (ctx) => service.openWorktree(ctx.ref),
      render: (r) => `已打开: ${r.opened}`,
    },
    {
      id: 'wt.context',
      cli: ['wt', 'context'],
      http: ['GET', '/api/wt/context'],
      summary: '一次性获取主项目的最新 git 上下文（分支/改动/领先落后/扩展）',
      flags: { log: { type: 'number', default: 5, hint: '最近提交条数' } },
      run: (ctx) => service.getContext({ log: ctx.log }),
      render: renderContext,
    },
    {
      id: 'wt.rebase',
      cli: ['wt', 'rebase'],
      http: ['POST', '/api/wt/rebase'],
      summary: '把工作树 rebase 到主项目当前分支；脏树给 --message 自动提交',
      args: [{ name: 'ref', required: false }],
      flags: {
        base: { type: 'string', hint: '基础分支' },
        message: { type: 'string', hint: '自动提交信息' },
      },
      run: (ctx) => service.rebaseWorktree(ctx),
      render: renderRebase,
    },
    {
      id: 'wt.fanout',
      cli: ['wt', 'fanout'],
      http: ['POST', '/api/wt/fanout'],
      summary: '把主项目当前分支同步（rebase）到全部工作树；先出计划，--yes 执行',
      flags: {
        base: { type: 'string', hint: '基础分支' },
        yes: { type: 'boolean', hint: '执行计划' },
      },
      run: (ctx) => service.fanout({ base: ctx.base, yes: ctx.yes === true }),
      render: renderFanout,
    },
    {
      id: 'wt.ext.list',
      cli: ['wt', 'ext', 'list'],
      http: ['GET', '/api/wt/ext'],
      summary: '扩展文件清单及其在主项目/当前工作树的状态',
      flags: { target: { type: 'string', hint: '评估指定工作树' } },
      run: (ctx) => service.listExtensions({ target: ctx.target }),
      render: renderExtList,
    },
    {
      id: 'wt.ext.add',
      cli: ['wt', 'ext', 'add'],
      http: ['POST', '/api/wt/ext'],
      summary: '按全路径登记一个被 git 忽略的文件/目录为扩展文件',
      args: ['abspath'],
      flags: { label: { type: 'string' }, force: { type: 'boolean' } },
      run: (ctx) => service.addExtension(ctx),
      render: renderExtAdded,
    },
    {
      id: 'wt.ext.discover',
      cli: ['wt', 'ext', 'discover'],
      http: ['POST', '/api/wt/ext/discover'],
      summary: '从 .gitignore 与 git 发现被忽略文件；默认只建议，--apply 登记',
      flags: { apply: { type: 'boolean', hint: '登记全部候选' } },
      run: (ctx) => service.discoverExtensions({ apply: ctx.apply === true }),
      render: renderDiscover,
    },
    {
      id: 'wt.ext.get',
      cli: ['wt', 'ext', 'get'],
      http: ['GET', '/api/wt/ext/:ref'],
      summary: '查看单个扩展文件登记与当前状态',
      args: ['ref'],
      run: (ctx) => service.getExtension(ctx.ref),
      render: (r) => renderExtAdded(r),
    },
    {
      id: 'wt.ext.update',
      cli: ['wt', 'ext', 'update'],
      http: ['PATCH', '/api/wt/ext/:ref'],
      summary: '修改扩展文件标签',
      args: ['ref'],
      flags: { label: { type: 'string' } },
      run: (ctx) => service.updateExtension(ctx.ref, { label: ctx.label }),
      render: renderExtUpdated,
    },
    {
      id: 'wt.ext.remove',
      cli: ['wt', 'ext', 'remove'],
      http: ['DELETE', '/api/wt/ext/:ref'],
      summary: '移除扩展文件登记（磁盘不动）',
      args: ['ref'],
      run: (ctx) => service.removeExtension(ctx.ref),
      render: renderExtRemoved,
    },
  ],
};

